#!/bin/bash
echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

#docker login -u "$DOCKERHUB_USERNAME" -p  "$DOCKERHUB_PASSWORD"
docker tag  ligo_web novavic/ligo_web
docker push novavic/ligo_web:latest
docker tag ligo_celeryworker novavic/ligo_celeryworker
docker push novavic/ligo_celeryworker:latest
