# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0002_linkingproject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkingstep',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the linking step'),
        ),
    ]
