# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0003_auto_20170126_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingstep',
            name='group',
            field=models.BooleanField(default=True, verbose_name='Dedup Entity Group Flag'),
        ),
    ]
