# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0004_linkingstep_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkingdataset',
            options={'ordering': ['link_seq']},
        ),
        migrations.RemoveField(
            model_name='linkingstep',
            name='description',
        ),
        migrations.RemoveField(
            model_name='linkingstep',
            name='linking_method',
        ),
        migrations.RemoveField(
            model_name='linkingstep',
            name='name',
        ),
        migrations.AddField(
            model_name='linkingproject',
            name='linking_method',
            field=models.CharField(choices=[('DTR', 'Deterministic'), ('PRB', 'Probabilistic')], default='DTR', max_length=3, verbose_name='Linking Method'),
        ),
    ]
