# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0005_auto_20170129_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingproject',
            name='results_url',
            field=models.URLField(blank=True, verbose_name='Project summary file url'),
        ),
        migrations.AddField(
            model_name='linkingproject',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'In Progress'), ('COMPLETED', 'Completed')], default='READY', max_length=10, verbose_name='Project Status'),
        ),
    ]
