# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0006_auto_20170206_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkingproject',
            name='results_url',
        ),
        migrations.AddField(
            model_name='linkingproject',
            name='results_file',
            field=models.CharField(blank=True, max_length=255, verbose_name='Project summary file'),
        ),
    ]
