FROM python:3.6
ENV PYTHONUNBUFFERED 1

#Docker file for forming local/dev Django container
RUN mkdir -p /user_data/media/datasets /user_data/media/linking
RUN mkdir /tmp/django-email-dev
# Ownership change not a requirement for local/dev docker environments
RUN chmod -R 0777 /user_data

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./web-app/requirements /usr/src/app/requirements
RUN pip install -r /usr/src/app/requirements/local.txt

COPY ./web-app/compose/django/entrypoint.sh /usr/src/app/entrypoint.sh
RUN sed -i 's/\r//' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

COPY ./web-app/compose/django/start-dev.sh /usr/src/app/start-dev.sh
RUN sed -i 's/\r//' /usr/src/app/start-dev.sh
RUN chmod +x /usr/src/app/start-dev.sh

COPY ./web-app /usr/src/app

RUN echo 'django:x:999:999:django:/:/bin/sh' >> /etc/passwd

RUN chown 999:999 /usr/src/app/entrypoint.sh
RUN chown 999:999 /usr/src/app/start-dev.sh

RUN chown 999:999 -R /usr/src/app
RUN chown 999:999 -R /user_data
RUN chown 999:999 -R /tmp

#USER django
USER "999:999"

WORKDIR /usr/src/app

ENTRYPOINT ["./entrypoint.sh"]
