FROM python:3.6
ENV PYTHONUNBUFFERED 1

ARG APP_VERSION
ENV APP_VERSION=${APP_VERSION}

#Docker file for forming local/dev Django container
RUN mkdir -p /user_data/media/datasets /user_data/media/linking
RUN mkdir /tmp/django-email-dev
# Ownership change not a requirement for local/dev docker environments
RUN chmod -R 0777 /user_data

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./web-app/requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./web-app/compose/django/entrypoint.sh /linkage/entrypoint.sh
RUN sed -i 's/\r//' /linkage/entrypoint.sh
RUN chmod +x /linkage/entrypoint.sh

COPY ./web-app/compose/django/start-dev.sh /linkage/start-dev.sh
RUN sed -i 's/\r//' /linkage/start-dev.sh
RUN chmod +x /linkage/start-dev.sh

COPY ./web-app /linkage

RUN echo 'django:x:999:999:django:/:/bin/sh' >> /etc/passwd

RUN chown 999:999 /linkage/entrypoint.sh
RUN chown 999:999 /linkage/start-dev.sh

RUN chown 999:999 -R /linkage
RUN chown 999:999 -R /user_data
RUN chown 999:999 -R /tmp
#RUN echo "version=$(git describe --always)" >>/linkage/version.py
#USER django
USER "999:999"

WORKDIR /linkage

ENTRYPOINT ["/linkage/entrypoint.sh"]
