# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkingDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_seq', models.IntegerField()),
                ('columns', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('index_field', models.CharField(max_length=255, verbose_name='Index Field')),
                ('entity_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Entity identifier Field')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset')),
            ],
            options={
                'ordering': ['link_seq'],
            },
        ),
        migrations.CreateModel(
            name='LinkingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Lnking project name')),
                ('type', models.CharField(choices=[('DEDEUP', 'De-Duplication'), ('LINK', 'Data Linkage')], default='LINK', max_length=10, verbose_name='Project Type')),
                ('description', models.TextField(blank=True, verbose_name='Linking Project description')),
                ('relationship_type', models.CharField(choices=[('1T1', 'One to One'), ('1TM', 'One to Many'), ('MT1', 'Many to One')], default='1T1', max_length=3, verbose_name='Linking Relationship type')),
                ('linked_url', models.URLField(verbose_name='Linked output file')),
                ('matched_url', models.URLField(verbose_name='Matched but not linked records file')),
                ('results_file', models.CharField(blank=True, max_length=255, verbose_name='Project summary file')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('READY', 'Ready'), ('RUNNING', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=10, verbose_name='Project Status')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='Project task id')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('datasets', models.ManyToManyField(through='linking.LinkingDataset', to='datasets.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='LinkingStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('blocking_schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('linking_schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('group', models.BooleanField(default=True, verbose_name='Dedup Entity Group Flag')),
                ('linking_method', models.CharField(choices=[('DTR', 'Deterministic'), ('PRB', 'Probabilistic')], default='DTR', max_length=3, verbose_name='Linking Method')),
                ('linking_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='linking.LinkingProject')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddField(
            model_name='linkingdataset',
            name='link_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linking.LinkingProject'),
        ),
    ]
