# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 00:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkingDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_seq', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='LinkingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Lnking project name')),
                ('description', models.TextField(blank=True, verbose_name='Linking Project description')),
                ('relationship_type', models.CharField(choices=[('1T1', 'One to One'), ('1TM', 'One to Many'), ('MT1', 'Many to One')], default='1T1', max_length=3, verbose_name='Linking Relationship type')),
                ('linked_url', models.URLField(verbose_name='Linked output file')),
                ('matched_url', models.URLField(verbose_name='Matched but not linked records file')),
                ('datasets', models.ManyToManyField(through='linking.LinkingDataset', to='datasets.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='LinkingStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name of the linking step')),
                ('seq', models.IntegerField()),
                ('description', models.TextField(blank=True, verbose_name='Linking Step note')),
                ('linking_method', models.CharField(choices=[('DTR', 'Deterministic'), ('PRB', 'Probabilistic')], default='DTR', max_length=3, verbose_name='Linking Method')),
                ('blocking_schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('linking_schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('linking_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='linking.LinkingProject')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddField(
            model_name='linkingdataset',
            name='link_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linking.LinkingProject'),
        ),
    ]
