# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingproject',
            name='type',
            field=models.CharField(choices=[('DEDEUP', 'De-Duplication'), ('LINK', 'Data Linkage')], default='LINK', max_length=10, verbose_name='Project Type'),
        ),
    ]
