# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0007_auto_20170207_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkingproject',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='linkingproject',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='READY', max_length=10, verbose_name='Project Status'),
        ),
    ]
