# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0009_linkingdataset_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkingproject',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('READY', 'Ready'), ('RUNNING', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=10, verbose_name='Project Status'),
        ),
    ]
