# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0010_auto_20170306_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkingproject',
            name='linking_method',
        ),
        migrations.AddField(
            model_name='linkingstep',
            name='linking_method',
            field=models.CharField(choices=[('DTR', 'Deterministic'), ('PRB', 'Probabilistic')], default='DTR', max_length=3, verbose_name='Linking Method'),
        ),
    ]
